version: '3.4'

services:
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=bestestapi
      - POSTGRES_PASSWORD=bestestapi
      - POSTGRES_DB=bestestapi
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql
  redis:
    image: redis:3.2.11-alpine
    ports:
      - 6379:6379
volumes:
  db-data:
